"""add nonce to blocks

Revision ID: 1e7e4b033bd6
Revises: f494b1b603cf
Create Date: 2026-07-29 00:17:09.222532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7e4b033bd6'
down_revision: Union[str, None] = 'f494b1b603cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('nonce', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'nonce')
    # ### end Alembic commands ###
