"""add fee to transactions

Revision ID: 753f79042c54
Revises: 2359d827e9ba
Create Date: 2026-07-29 11:04:32.019692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753f79042c54'
down_revision: Union[str, None] = '2359d827e9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fee', sa.Numeric(precision=18, scale=8), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'fee')
    # ### end Alembic commands ###
