"""add signature to transactions

Revision ID: f494b1b603cf
Revises: 2a0af7913890
Create Date: 2026-07-29 00:02:02.298741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f494b1b603cf'
down_revision: Union[str, None] = '2a0af7913890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('signature', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'signature')
    # ### end Alembic commands ###
